# Generated by Django 5.1.15 on 2025-12-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alloy',
            fields=[
                ('alloy_id', models.AutoField(primary_key=True, serialize=False)),
                ('alloy_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('density', models.DecimalField(decimal_places=4, help_text='Density in lbs/in³', max_digits=10)),
            ],
            options={
                'db_table': 'alloys',
                'ordering': ['alloy_code'],
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_number', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Capacity in lbs/hr', max_digits=10)),
            ],
            options={
                'db_table': 'lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_number', models.CharField(choices=[('1', 'First Shift'), ('2', 'Second Shift'), ('3', 'Third Shift')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'shifts',
                'ordering': ['shift_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='general', max_length=50)),
            ],
            options={
                'db_table': 'system_options',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Temper',
            fields=[
                ('temper_id', models.AutoField(primary_key=True, serialize=False)),
                ('temper_code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tempers',
                'ordering': ['temper_code'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('table_name', models.CharField(blank=True, max_length=100)),
                ('record_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
