# Generated by Django 5.1.15 on 2025-12-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('part_description', models.CharField(max_length=200)),
                ('customer_po', models.CharField(blank=True, max_length=100)),
                ('order_line', models.CharField(blank=True, max_length=50)),
                ('ordered_quantity', models.IntegerField()),
                ('produced_quantity', models.IntegerField(default=0)),
                ('scrap_quantity', models.IntegerField(default=0)),
                ('target_gauge', models.DecimalField(decimal_places=4, max_digits=10)),
                ('target_width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('target_length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='customers.customer')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.line')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.shift')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downtime_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('TOOLING', 'Tooling'), ('MATERIAL', 'Material Issue'), ('QUALITY', 'Quality Issue'), ('CHANGEOVER', 'Job Changeover'), ('OTHER', 'Other')], max_length=20)),
                ('cause', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('corrective_action', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='core.line')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='production.job')),
            ],
            options={
                'db_table': 'downtime',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='JobCoil',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_coil_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(default=0)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('coil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_coils', to='inventory.coil')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_coils', to='production.job')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_coils',
                'ordering': ['job', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('production_date', models.DateField(db_index=True)),
                ('total_pieces', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scrap_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheduled_runtime', models.DecimalField(decimal_places=2, help_text='Hours', max_digits=6)),
                ('actual_runtime', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('downtime', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('efficiency_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.line')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shift')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_production',
                'ordering': ['-production_date', 'line'],
                'unique_together': {('production_date', 'line', 'shift')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'status'], name='jobs_custome_604e59_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['line', 'status'], name='jobs_line_id_55ec6e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scheduled_start'], name='jobs_schedul_d93dda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobcoil',
            unique_together={('job', 'coil')},
        ),
    ]
