# Generated by Django 5.1.14 on 2025-11-25 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "__first__"),
        ("production", "__first__"),
        ("shipping", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EDIPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "edi_id",
                    models.CharField(
                        help_text="Trading partner EDI identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "qualifier",
                    models.CharField(
                        choices=[
                            ("01", "01 - DUNS (Dun & Bradstreet)"),
                            ("02", "02 - SCAC (Standard Carrier Alpha Code)"),
                            ("ZZ", "ZZ - Mutually Defined"),
                        ],
                        default="ZZ",
                        max_length=2,
                    ),
                ),
                (
                    "supports_856",
                    models.BooleanField(
                        default=False, help_text="Ship Notice/Manifest"
                    ),
                ),
                (
                    "supports_863",
                    models.BooleanField(
                        default=False, help_text="Material Test Report"
                    ),
                ),
                (
                    "supports_870",
                    models.BooleanField(default=False, help_text="Order Status Report"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for EDI notifications",
                        max_length=254,
                    ),
                ),
                ("ftp_host", models.CharField(blank=True, max_length=255)),
                ("ftp_username", models.CharField(blank=True, max_length=100)),
                ("ftp_path", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "edi_partner",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="EDI856ShipNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_identifier",
                    models.CharField(
                        help_text="Shipment identification number", max_length=50
                    ),
                ),
                ("shipment_date", models.DateField()),
                ("shipment_time", models.TimeField(blank=True, null=True)),
                ("carrier_code", models.CharField(blank=True, max_length=10)),
                ("carrier_name", models.CharField(blank=True, max_length=255)),
                ("bol_number", models.CharField(blank=True, max_length=50)),
                ("pro_number", models.CharField(blank=True, max_length=50)),
                ("ship_from_name", models.CharField(blank=True, max_length=255)),
                ("ship_from_address", models.TextField(blank=True)),
                ("ship_to_name", models.CharField(blank=True, max_length=255)),
                ("ship_to_address", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edi_notices",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "db_table": "edi_856_ship_notice",
                "ordering": ["-shipment_date"],
            },
        ),
        migrations.CreateModel(
            name="EDI856Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("item_number", models.CharField(max_length=100)),
                ("item_description", models.CharField(blank=True, max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_of_measure", models.CharField(default="LB", max_length=10)),
                ("pack_count", models.IntegerField(default=1)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("coil_number", models.CharField(blank=True, max_length=50)),
                ("heat_number", models.CharField(blank=True, max_length=50)),
                (
                    "ship_notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="edi.edi856shipnotice",
                    ),
                ),
            ],
            options={
                "db_table": "edi_856_item",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="EDITransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("856", "856 - Ship Notice/Manifest"),
                            ("863", "863 - Material Test Report"),
                            ("870", "870 - Order Status Report"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SENT", "Sent"),
                            ("RECEIVED", "Received"),
                            ("ERROR", "Error"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "control_number",
                    models.CharField(
                        help_text="ISA/GS control number", max_length=50, unique=True
                    ),
                ),
                ("raw_data", models.TextField(help_text="Raw EDI X12 format data")),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, help_text="Parsed EDI data as JSON", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="edi.edipartner",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "edi_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EDILog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="edi.editransaction",
                    ),
                ),
            ],
            options={
                "db_table": "edi_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EDI870OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=50, unique=True)),
                ("report_date", models.DateField()),
                ("customer_po", models.CharField(blank=True, max_length=50)),
                ("job_number_text", models.CharField(max_length=50)),
                ("order_status", models.CharField(max_length=50)),
                (
                    "quantity_ordered",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_completed",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "quantity_shipped",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("scheduled_ship_date", models.DateField(blank=True, null=True)),
                ("estimated_completion_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edi_status_reports",
                        to="production.job",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_status",
                        to="edi.editransaction",
                    ),
                ),
            ],
            options={
                "db_table": "edi_870_order_status",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="EDI863TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=50, unique=True)),
                ("report_date", models.DateField()),
                ("heat_number", models.CharField(max_length=50)),
                ("coil_number", models.CharField(max_length=50)),
                ("product_description", models.TextField(blank=True)),
                ("alloy", models.CharField(blank=True, max_length=50)),
                ("temper", models.CharField(blank=True, max_length=50)),
                (
                    "gauge",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("chemical_composition", models.JSONField(default=dict)),
                ("mechanical_properties", models.JSONField(default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "coil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edi_test_reports",
                        to="inventory.coil",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_report",
                        to="edi.editransaction",
                    ),
                ),
            ],
            options={
                "db_table": "edi_863_test_report",
                "ordering": ["-report_date"],
            },
        ),
        migrations.AddField(
            model_name="edi856shipnotice",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ship_notice",
                to="edi.editransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="editransaction",
            index=models.Index(
                fields=["transaction_type", "status"],
                name="edi_transac_transac_c92150_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="editransaction",
            index=models.Index(
                fields=["control_number"], name="edi_transac_control_7fe164_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="edilog",
            index=models.Index(
                fields=["level", "-created_at"], name="edi_log_level_22a70e_idx"
            ),
        ),
    ]
