# Generated by Django 5.1.15 on 2025-12-03 17:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coil_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_coil_number', models.CharField(db_index=True, max_length=50)),
                ('abc_coil_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('supplier_coil_number', models.CharField(blank=True, max_length=50)),
                ('gauge', models.DecimalField(decimal_places=4, help_text='Thickness in inches', max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, help_text='Width in inches', max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, help_text='Total weight in lbs', max_digits=12)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=2, help_text='Net weight in lbs', max_digits=12)),
                ('outside_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inside_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('heat_treatment', models.CharField(blank=True, max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('received_date', models.DateField()),
                ('receiving_number', models.CharField(blank=True, max_length=50)),
                ('mill_certificate', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('AVAILABLE', 'Available for Processing'), ('IN_PROCESS', 'In Process'), ('PROCESSED', 'Processed'), ('ON_HOLD', 'On Hold'), ('REJECTED', 'Rejected'), ('SHIPPED', 'Shipped')], default='RECEIVED', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Physical warehouse location', max_length=100)),
                ('qa_approved', models.BooleanField(default=False)),
                ('qa_hold', models.BooleanField(default=False)),
                ('qa_notes', models.TextField(blank=True)),
                ('has_863_report', models.BooleanField(default=False)),
                ('edi_sent_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('alloy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.alloy')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coils', to='customers.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_coils', to='customers.customer')),
                ('temper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.temper')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coils',
                'ordering': ['-received_date', 'abc_coil_number'],
            },
        ),
        migrations.CreateModel(
            name='CoilHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('coil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.coil')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coil_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapSkid',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scrap_skid_id', models.AutoField(primary_key=True, serialize=False)),
                ('scrap_skid_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scrap_type', models.CharField(choices=[('EDGE_TRIM', 'Edge Trim'), ('SKELETON', 'Skeleton'), ('REJECTS', 'Rejects'), ('PROCESS_SCRAP', 'Process Scrap'), ('OTHER', 'Other')], max_length=20)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('AVAILABLE', 'Available for Sale'), ('ASSIGNED', 'Assigned to Shipment'), ('SHIPPED', 'Shipped')], default='IN_PROGRESS', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('production_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_skids', to='customers.customer')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrap_skids', to='shipping.shipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scrap_skids',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='Skid',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skid_id', models.AutoField(primary_key=True, serialize=False)),
                ('skid_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('package_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tare_weight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('piece_count', models.IntegerField(default=0)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('QC_HOLD', 'QC Hold'), ('AVAILABLE', 'Available for Shipment'), ('ASSIGNED', 'Assigned to Shipment'), ('SHIPPED', 'Shipped')], default='IN_PROGRESS', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('production_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('qa_approved', models.BooleanField(default=False)),
                ('qa_inspector', models.CharField(blank=True, max_length=100)),
                ('qa_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skids', to='customers.customer')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skids', to='shipping.shipment')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skids',
                'ordering': ['-production_date', 'skid_number'],
            },
        ),
        migrations.AddIndex(
            model_name='coil',
            index=models.Index(fields=['customer', 'status'], name='coils_custome_db1644_idx'),
        ),
        migrations.AddIndex(
            model_name='coil',
            index=models.Index(fields=['received_date'], name='coils_receive_77cfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='coil',
            index=models.Index(fields=['abc_coil_number'], name='coils_abc_coi_b6198d_idx'),
        ),
        migrations.AddIndex(
            model_name='skid',
            index=models.Index(fields=['customer', 'status'], name='skids_custome_769f53_idx'),
        ),
        migrations.AddIndex(
            model_name='skid',
            index=models.Index(fields=['production_date'], name='skids_product_a6c6a9_idx'),
        ),
    ]
