# Generated by Django 5.1.15 on 2025-12-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('bol_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ship_to_name', models.CharField(max_length=200)),
                ('ship_to_address1', models.CharField(max_length=200)),
                ('ship_to_address2', models.CharField(blank=True, max_length=200)),
                ('ship_to_city', models.CharField(max_length=100)),
                ('ship_to_state', models.CharField(max_length=50)),
                ('ship_to_zip', models.CharField(max_length=20)),
                ('ship_to_country', models.CharField(default='USA', max_length=50)),
                ('trailer_number', models.CharField(blank=True, max_length=50)),
                ('seal_number', models.CharField(blank=True, max_length=50)),
                ('pro_number', models.CharField(blank=True, max_length=50)),
                ('ship_date', models.DateField(db_index=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pieces', models.IntegerField(default=0)),
                ('total_skids', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready to Ship'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='OPEN', max_length=20)),
                ('edi_856_sent', models.BooleanField(default=False)),
                ('edi_856_sent_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='customers.carrier')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='customers.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-ship_date', 'bol_number'],
            },
        ),
        migrations.CreateModel(
            name='EDITransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edi_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('856', 'ASN - Advanced Ship Notice'), ('863', 'Report of Test Results'), ('870', 'Order Status Report')], max_length=10)),
                ('control_number', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('edi_content', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edi_transactions', to='customers.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edi_transactions', to='shipping.shipment')),
            ],
            options={
                'db_table': 'edi_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['customer', 'status'], name='shipments_custome_4e5e77_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['ship_date'], name='shipments_ship_da_e29271_idx'),
        ),
        migrations.AddIndex(
            model_name='editransaction',
            index=models.Index(fields=['customer', 'transaction_type'], name='edi_transac_custome_3c0e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='editransaction',
            index=models.Index(fields=['status'], name='edi_transac_status_2aac99_idx'),
        ),
    ]
