# Generated by Django 5.1.15 on 2025-12-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_ON_HOLD', 'Job On Hold'), ('SHIPMENT_CREATED', 'Shipment Created'), ('SHIPMENT_SHIPPED', 'Shipment Shipped'), ('QA_FAILED', 'QA Test Failed'), ('QA_PASSED', 'QA Test Passed'), ('INVENTORY_LOW', 'Low Inventory Alert'), ('INVENTORY_RECEIVED', 'Inventory Received'), ('CUSTOMER_ORDER', 'New Customer Order'), ('MAINTENANCE_DUE', 'Maintenance Due'), ('DOWNTIME_ALERT', 'Production Downtime')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(help_text='Plain text version')),
                ('body_html', models.TextField(help_text='HTML version with template variables like {job_number}, {customer_name}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_job_started', models.BooleanField(default=True)),
                ('email_job_completed', models.BooleanField(default=True)),
                ('email_job_on_hold', models.BooleanField(default=True)),
                ('email_shipment_created', models.BooleanField(default=True)),
                ('email_shipment_shipped', models.BooleanField(default=True)),
                ('email_qa_failed', models.BooleanField(default=True)),
                ('email_qa_passed', models.BooleanField(default=False)),
                ('email_inventory_low', models.BooleanField(default=True)),
                ('email_inventory_received', models.BooleanField(default=False)),
                ('email_customer_order', models.BooleanField(default=True)),
                ('email_maintenance_due', models.BooleanField(default=True)),
                ('email_downtime_alert', models.BooleanField(default=True)),
                ('app_enabled', models.BooleanField(default=True)),
                ('app_job_started', models.BooleanField(default=True)),
                ('app_job_completed', models.BooleanField(default=True)),
                ('app_job_on_hold', models.BooleanField(default=True)),
                ('app_shipment_created', models.BooleanField(default=True)),
                ('app_shipment_shipped', models.BooleanField(default=True)),
                ('app_qa_failed', models.BooleanField(default=True)),
                ('app_qa_passed', models.BooleanField(default=True)),
                ('app_inventory_low', models.BooleanField(default=True)),
                ('app_inventory_received', models.BooleanField(default=True)),
                ('app_customer_order', models.BooleanField(default=True)),
                ('app_maintenance_due', models.BooleanField(default=True)),
                ('app_downtime_alert', models.BooleanField(default=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_ON_HOLD', 'Job On Hold'), ('SHIPMENT_CREATED', 'Shipment Created'), ('SHIPMENT_SHIPPED', 'Shipment Shipped'), ('QA_FAILED', 'QA Test Failed'), ('QA_PASSED', 'QA Test Passed'), ('INVENTORY_LOW', 'Low Inventory Alert'), ('INVENTORY_RECEIVED', 'Inventory Received'), ('CUSTOMER_ORDER', 'New Customer Order'), ('MAINTENANCE_DUE', 'Maintenance Due'), ('DOWNTIME_ALERT', 'Production Downtime')], max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('html_message', models.TextField(blank=True, null=True)),
                ('job_id', models.CharField(blank=True, max_length=50, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('coil_id', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('READ', 'Read')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx')],
            },
        ),
    ]
